---
title: "Gov 50 Final Project"
author: "Kaitlyn Vu"
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---



Over the past decade, how has political ideology affected changing public approval of the Supreme Court? In my final project, I plan to examine the relationship between political partisanship and public opinion of the Supreme Court.  I hypothesize that individuals who identify as liberal (Democrats) are more likely to disapprove of the Court than those that identify as conservative (Republican). Overall, I expect that public approval of the Court has decreased across both parties over the past 10 years. For context, the Supreme Court is now more conservative than it has ever been in the past 90 years: with the appointment and confirmation of three conservative justices, former President Donald Trump filled more seats in a single term than any president since Franklin Delano Roosevelt. As such, a majority of Americans currently feel a disconnect from the Court as recent controversial decisions on topics such as abortion, environmental regulations, and affirmative action appear to run contrary to popular opinion. I’m planning to work with survey data from Pew Research Center’s American Trends Panel Wave 101, which was fielded in January 2022. The dataset has a tracking question (“Do you have a favorable or unfavorable opinion of each of the following?”) that asks respondents for their approval of the various governmental institutions, of which includes the Supreme Court—the project will focus on responses from 2012-2022. My explanatory variable of interest is the political ideology of the respondents: the variable can be coded =1 for liberal and =0 for conservative. My outcome variable is changes in the favorability of respondents’ opinion towards the Supreme Court (based on political ideology), which I can measure by calculating percent change or measuring linear regression. If I observe a larger percent change in unfavorable approval ratings for the Supreme Court among liberals than conservatives over 10 years, this would support my hypothesis. On the other hand, If I observe a larger percent change in unfavorable approval ratings for the Supreme Court among conservatives than liberals over 10 years, this would provide evidence against my hypothesis. 